; PlatformIO Project Configuration File for Anti-Theft Locker System
; Target: ESP32 DevKit V4 / Arduino Framework

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.10
    adafruit/Adafruit GFX Library@^1.11.9
    chris--a/Keypad@^3.1.1
    madhephaestus/ESP32Servo@^3.0.5
